#!/usr/bin/python3
"""This module defines a Square class."""
class Square:
    """This class defines a square."""
    def __init__(self, size=0):
        """Initialize a square."""
        if size < 0:
            """first condition."""
           raise ValueError('size must be >= 0')
        if type(size) is not int:
           raise TypeError('size must be an integer')
        self.__size = size
